/*
 * ADCSConnector
 * baseline API to request and revoce certificates from an ADCS instace
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: kuehne@trustable.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.trustable.ca3s.client.api;

import static org.junit.Assert.assertNotNull;

import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import de.trustable.ca3s.client.model.GetCertificateResponse;
import de.trustable.ca3s.client.model.JWSWrappedRequest;
import io.swagger.client.ApiException;

/**
 * API tests for Ca3sApi
 */
public class Ca3sApiTest {

    private final RemoteADCSClient api = new RemoteADCSClient("http://localhost:9090/ADCSConnector/", "secretApiKey");

    /**
     * get details of a certificate request identified by its Id
     *
     * details of a certificate request identified by its Id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    @Ignore
    public void getRequestByIdTest() throws ApiException {
    	
        String reqId = "1";
        GetCertificateResponse response = api.getRequestById(reqId);

        assertNotNull(response);

    }
    /**
     * get the list certificate request IDs
     *
     * enumerate all the request (issued or pending) available the ADCS
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    @Ignore
    public void getRequestIdListTest() throws ApiException {
    	
        Integer offset = 0;
        Integer limit = 10;
        
        List<String> response = api.getRequestIdList(offset, limit);
        assertNotNull(response);
        
    }
    
    /**
     * revoke a certificate
     *
     * revoke a certificate from the ADCS
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Ignore
    @Test
    public void revokeCertificateTest() throws ApiException {
        JWSWrappedRequest jwtBody = null;

        api.revokeCertificate(jwtBody);

        // TODO: test validations
    }
}
