/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.trustable.ca3s.adcs.proxy.web.rest;


import javax.validation.Valid;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;


@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-10-20T18:45:40.714Z[GMT]")
@Tag(name = "adcsCertificateRevoker", description = "the adcsCertificateRevoker API")
public interface AdcsCertificateRevokerApi {

    @Operation(summary = "revoke a certificate",
        description = "revoke a certificate issued by the local ADCS. The request parameter are wrapped into Javascript Web Signature",
        responses = {
        @ApiResponse(responseCode = "204", description = "certificate revoked"),
        @ApiResponse(responseCode = "400", description = "invalid input, object invalid"),
        @ApiResponse(responseCode = "401", description = "authentication / authorization missing, especially JWS invalid"),
        @ApiResponse(responseCode = "409", description = "certificate already revoked") })
    @RequestMapping(value = "/adcsCertificateRevoker",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> revokeCertificate(@Parameter(description = "serial, reason and revocation date wrapped in a JWS"  )  @Valid @RequestBody JWSWrappedRequest body);

}
