/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.trustable.ca3s.adcs.proxy.web.rest;


import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import de.trustable.ca3s.adcs.proxy.web.dto.GetCertificateResponse;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-08-30T11:55:34.168Z[GMT]")
@Tag(name = "adcsRequest", description = "the adcsRequest API")
public interface AdcsRequestApi {

    @Operation(summary = "get details of a certificate request identified by its Id", description ="details of a certificate request identified by its Id",
        responses = {
            @ApiResponse(responseCode = "200", description = "request id found"),
            @ApiResponse(responseCode = "400", description = "invalid input, object invalid"),
            @ApiResponse(responseCode = "401", description = "authentication / authorization missing"),
            @ApiResponse(responseCode = "404", description = "no existing item for the given id") }
        )
    @RequestMapping(value = "/adcsRequest/{reqId}",
        produces = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<GetCertificateResponse> getRequestById(@Parameter(description = "certificate request id",required=true) @PathVariable("reqId") String reqId);

}
