package de.trustable.ca3s.adcs.proxy;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import javax.annotation.Generated;

<<<<<<< HEAD
@Generated(value = "JHipster", comments = "Generated by JHipster 7.0.1")
=======
@Generated(value = "JHipster", comments = "Generated by JHipster 7.2.0")
>>>>>>> jhipster_upgrade
@Retention(RetentionPolicy.SOURCE)
@Target({ ElementType.TYPE })
public @interface GeneratedByJHipster {
}
