/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.trustable.ca3s.adcs.proxy.web.rest;


import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import de.trustable.ca3s.adcs.proxy.web.dto.GetCertificateResponse;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.Authorization;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-08-30T11:55:34.168Z[GMT]")
@Api(value = "adcsRequest", description = "the adcsRequest API")
public interface AdcsRequestApi {

    @ApiOperation(value = "get details of a certificate request identified by its Id", nickname = "getRequestById", notes = "details of a certificate request identified by its Id", response = GetCertificateResponse.class, authorizations = {
            @Authorization(value = "APIKeyHeader")
        }, tags={ "ADCSProxy", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "request id found", response = GetCertificateResponse.class),
        @ApiResponse(code = 400, message = "invalid input, object invalid"),
        @ApiResponse(code = 401, message = "authentication / authorization missing"),
        @ApiResponse(code = 404, message = "no existing item for the given id") })
    @RequestMapping(value = "/adcsRequest/{reqId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<GetCertificateResponse> getRequestById(@ApiParam(value = "certificate request id",required=true) @PathVariable("reqId") String reqId);

}
