/*
 * adcsProxy API
 * API to query the local ADCS instance and to request and revoke certificates from an ADCS instance
 *
 * OpenAPI spec version: 1.2.0-oas3
 * Contact: kuehne@trustable.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.trustable.ca3s.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

/**
 * ADCSInstanceDetailsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-12T08:23:03.544Z")
public class ADCSInstanceDetailsResponse {
  @SerializedName("caName")
  private String caName = null;

  @SerializedName("caType")
  private String caType = null;

  @SerializedName("dnsName")
  private String dnsName = null;

  @SerializedName("fileVersion")
  private String fileVersion = null;

  @SerializedName("parentCaName")
  private String parentCaName = null;

  @SerializedName("productVersion")
  private String productVersion = null;

  @SerializedName("signingCertChains")
  private List<String> signingCertChains = null;

  @SerializedName("signingCerts")
  private List<String> signingCerts = null;

  @SerializedName("subjectTemplateOIDs")
  private List<String> subjectTemplateOIDs = null;

  @SerializedName("templateOIDs")
  private List<String> templateOIDs = null;

  @SerializedName("templates")
  private List<String> templates = null;

  public ADCSInstanceDetailsResponse caName(String caName) {
    this.caName = caName;
    return this;
  }

   /**
   * Get caName
   * @return caName
  **/
  public String getCaName() {
    return caName;
  }

  public void setCaName(String caName) {
    this.caName = caName;
  }

  public ADCSInstanceDetailsResponse caType(String caType) {
    this.caType = caType;
    return this;
  }

   /**
   * Get caType
   * @return caType
  **/
  public String getCaType() {
    return caType;
  }

  public void setCaType(String caType) {
    this.caType = caType;
  }

  public ADCSInstanceDetailsResponse dnsName(String dnsName) {
    this.dnsName = dnsName;
    return this;
  }

   /**
   * Get dnsName
   * @return dnsName
  **/
  public String getDnsName() {
    return dnsName;
  }

  public void setDnsName(String dnsName) {
    this.dnsName = dnsName;
  }

  public ADCSInstanceDetailsResponse fileVersion(String fileVersion) {
    this.fileVersion = fileVersion;
    return this;
  }

   /**
   * Get fileVersion
   * @return fileVersion
  **/
  public String getFileVersion() {
    return fileVersion;
  }

  public void setFileVersion(String fileVersion) {
    this.fileVersion = fileVersion;
  }

  public ADCSInstanceDetailsResponse parentCaName(String parentCaName) {
    this.parentCaName = parentCaName;
    return this;
  }

   /**
   * Get parentCaName
   * @return parentCaName
  **/
  public String getParentCaName() {
    return parentCaName;
  }

  public void setParentCaName(String parentCaName) {
    this.parentCaName = parentCaName;
  }

  public ADCSInstanceDetailsResponse productVersion(String productVersion) {
    this.productVersion = productVersion;
    return this;
  }

   /**
   * Get productVersion
   * @return productVersion
  **/
  public String getProductVersion() {
    return productVersion;
  }

  public void setProductVersion(String productVersion) {
    this.productVersion = productVersion;
  }

  public ADCSInstanceDetailsResponse signingCertChains(List<String> signingCertChains) {
    this.signingCertChains = signingCertChains;
    return this;
  }

  public ADCSInstanceDetailsResponse addSigningCertChainsItem(String signingCertChainsItem) {
    if (this.signingCertChains == null) {
      this.signingCertChains = new ArrayList<String>();
    }
    this.signingCertChains.add(signingCertChainsItem);
    return this;
  }

   /**
   * Get signingCertChains
   * @return signingCertChains
  **/
  public List<String> getSigningCertChains() {
    return signingCertChains;
  }

  public void setSigningCertChains(List<String> signingCertChains) {
    this.signingCertChains = signingCertChains;
  }

  public ADCSInstanceDetailsResponse signingCerts(List<String> signingCerts) {
    this.signingCerts = signingCerts;
    return this;
  }

  public ADCSInstanceDetailsResponse addSigningCertsItem(String signingCertsItem) {
    if (this.signingCerts == null) {
      this.signingCerts = new ArrayList<String>();
    }
    this.signingCerts.add(signingCertsItem);
    return this;
  }

   /**
   * Get signingCerts
   * @return signingCerts
  **/
  public List<String> getSigningCerts() {
    return signingCerts;
  }

  public void setSigningCerts(List<String> signingCerts) {
    this.signingCerts = signingCerts;
  }

  public ADCSInstanceDetailsResponse subjectTemplateOIDs(List<String> subjectTemplateOIDs) {
    this.subjectTemplateOIDs = subjectTemplateOIDs;
    return this;
  }

  public ADCSInstanceDetailsResponse addSubjectTemplateOIDsItem(String subjectTemplateOIDsItem) {
    if (this.subjectTemplateOIDs == null) {
      this.subjectTemplateOIDs = new ArrayList<String>();
    }
    this.subjectTemplateOIDs.add(subjectTemplateOIDsItem);
    return this;
  }

   /**
   * Get subjectTemplateOIDs
   * @return subjectTemplateOIDs
  **/
  public List<String> getSubjectTemplateOIDs() {
    return subjectTemplateOIDs;
  }

  public void setSubjectTemplateOIDs(List<String> subjectTemplateOIDs) {
    this.subjectTemplateOIDs = subjectTemplateOIDs;
  }

  public ADCSInstanceDetailsResponse templateOIDs(List<String> templateOIDs) {
    this.templateOIDs = templateOIDs;
    return this;
  }

  public ADCSInstanceDetailsResponse addTemplateOIDsItem(String templateOIDsItem) {
    if (this.templateOIDs == null) {
      this.templateOIDs = new ArrayList<String>();
    }
    this.templateOIDs.add(templateOIDsItem);
    return this;
  }

   /**
   * Get templateOIDs
   * @return templateOIDs
  **/
  public List<String> getTemplateOIDs() {
    return templateOIDs;
  }

  public void setTemplateOIDs(List<String> templateOIDs) {
    this.templateOIDs = templateOIDs;
  }

  public ADCSInstanceDetailsResponse templates(List<String> templates) {
    this.templates = templates;
    return this;
  }

  public ADCSInstanceDetailsResponse addTemplatesItem(String templatesItem) {
    if (this.templates == null) {
      this.templates = new ArrayList<String>();
    }
    this.templates.add(templatesItem);
    return this;
  }

   /**
   * Get templates
   * @return templates
  **/
  public List<String> getTemplates() {
    return templates;
  }

  public void setTemplates(List<String> templates) {
    this.templates = templates;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ADCSInstanceDetailsResponse adCSInstanceDetailsResponse = (ADCSInstanceDetailsResponse) o;
    return Objects.equals(this.caName, adCSInstanceDetailsResponse.caName) &&
        Objects.equals(this.caType, adCSInstanceDetailsResponse.caType) &&
        Objects.equals(this.dnsName, adCSInstanceDetailsResponse.dnsName) &&
        Objects.equals(this.fileVersion, adCSInstanceDetailsResponse.fileVersion) &&
        Objects.equals(this.parentCaName, adCSInstanceDetailsResponse.parentCaName) &&
        Objects.equals(this.productVersion, adCSInstanceDetailsResponse.productVersion) &&
        Objects.equals(this.signingCertChains, adCSInstanceDetailsResponse.signingCertChains) &&
        Objects.equals(this.signingCerts, adCSInstanceDetailsResponse.signingCerts) &&
        Objects.equals(this.subjectTemplateOIDs, adCSInstanceDetailsResponse.subjectTemplateOIDs) &&
        Objects.equals(this.templateOIDs, adCSInstanceDetailsResponse.templateOIDs) &&
        Objects.equals(this.templates, adCSInstanceDetailsResponse.templates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caName, caType, dnsName, fileVersion, parentCaName, productVersion, signingCertChains, signingCerts, subjectTemplateOIDs, templateOIDs, templates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ADCSInstanceDetailsResponse {\n");
    
    sb.append("    caName: ").append(toIndentedString(caName)).append("\n");
    sb.append("    caType: ").append(toIndentedString(caType)).append("\n");
    sb.append("    dnsName: ").append(toIndentedString(dnsName)).append("\n");
    sb.append("    fileVersion: ").append(toIndentedString(fileVersion)).append("\n");
    sb.append("    parentCaName: ").append(toIndentedString(parentCaName)).append("\n");

    sb.append("    productVersion: ").append(toIndentedString(productVersion)).append("\n");
    sb.append("    signingCertChains: ").append(toIndentedString(signingCertChains)).append("\n");
    sb.append("    signingCerts: ").append(toIndentedString(signingCerts)).append("\n");
    sb.append("    subjectTemplateOIDs: ").append(toIndentedString(subjectTemplateOIDs)).append("\n");
    sb.append("    templateOIDs: ").append(toIndentedString(templateOIDs)).append("\n");
    sb.append("    templates: ").append(toIndentedString(templates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

