/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.trustable.ca3s.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * ADCSInstanceDetailsResponse
 */
@JsonPropertyOrder({
  ADCSInstanceDetailsResponse.JSON_PROPERTY_CA_NAME,
  ADCSInstanceDetailsResponse.JSON_PROPERTY_CA_TYPE,
  ADCSInstanceDetailsResponse.JSON_PROPERTY_PARENT_CA_NAME,
  ADCSInstanceDetailsResponse.JSON_PROPERTY_PRODUCT_VERSION,
  ADCSInstanceDetailsResponse.JSON_PROPERTY_FILE_VERSION,
  ADCSInstanceDetailsResponse.JSON_PROPERTY_DNS_NAME,
  ADCSInstanceDetailsResponse.JSON_PROPERTY_SIGNING_CERTS,
  ADCSInstanceDetailsResponse.JSON_PROPERTY_SIGNING_CERT_CHAINS,
  ADCSInstanceDetailsResponse.JSON_PROPERTY_TEMPLATES,
  ADCSInstanceDetailsResponse.JSON_PROPERTY_TEMPLATE_O_I_DS,
  ADCSInstanceDetailsResponse.JSON_PROPERTY_SUBJECT_TEMPLATE_O_I_DS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-01T16:42:19.029808700+02:00[Europe/Berlin]")
public class ADCSInstanceDetailsResponse {
  public static final String JSON_PROPERTY_CA_NAME = "caName";
  private String caName;

  public static final String JSON_PROPERTY_CA_TYPE = "caType";
  private String caType;

  public static final String JSON_PROPERTY_PARENT_CA_NAME = "parentCaName";
  private String parentCaName;

  public static final String JSON_PROPERTY_PRODUCT_VERSION = "productVersion";
  private String productVersion;

  public static final String JSON_PROPERTY_FILE_VERSION = "fileVersion";
  private String fileVersion;

  public static final String JSON_PROPERTY_DNS_NAME = "dnsName";
  private String dnsName;

  public static final String JSON_PROPERTY_SIGNING_CERTS = "signingCerts";
  private List<String> signingCerts = null;

  public static final String JSON_PROPERTY_SIGNING_CERT_CHAINS = "signingCertChains";
  private List<String> signingCertChains = null;

  public static final String JSON_PROPERTY_TEMPLATES = "templates";
  private List<String> templates = null;

  public static final String JSON_PROPERTY_TEMPLATE_O_I_DS = "templateOIDs";
  private List<String> templateOIDs = null;

  public static final String JSON_PROPERTY_SUBJECT_TEMPLATE_O_I_DS = "subjectTemplateOIDs";
  private List<String> subjectTemplateOIDs = null;

  public ADCSInstanceDetailsResponse() { 
  }

  public ADCSInstanceDetailsResponse caName(String caName) {
    this.caName = caName;
    return this;
  }

   /**
   * Get caName
   * @return caName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CA_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCaName() {
    return caName;
  }


  @JsonProperty(JSON_PROPERTY_CA_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCaName(String caName) {
    this.caName = caName;
  }


  public ADCSInstanceDetailsResponse caType(String caType) {
    this.caType = caType;
    return this;
  }

   /**
   * Get caType
   * @return caType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CA_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCaType() {
    return caType;
  }


  @JsonProperty(JSON_PROPERTY_CA_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCaType(String caType) {
    this.caType = caType;
  }


  public ADCSInstanceDetailsResponse parentCaName(String parentCaName) {
    this.parentCaName = parentCaName;
    return this;
  }

   /**
   * Get parentCaName
   * @return parentCaName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARENT_CA_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getParentCaName() {
    return parentCaName;
  }


  @JsonProperty(JSON_PROPERTY_PARENT_CA_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParentCaName(String parentCaName) {
    this.parentCaName = parentCaName;
  }


  public ADCSInstanceDetailsResponse productVersion(String productVersion) {
    this.productVersion = productVersion;
    return this;
  }

   /**
   * Get productVersion
   * @return productVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRODUCT_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProductVersion() {
    return productVersion;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductVersion(String productVersion) {
    this.productVersion = productVersion;
  }


  public ADCSInstanceDetailsResponse fileVersion(String fileVersion) {
    this.fileVersion = fileVersion;
    return this;
  }

   /**
   * Get fileVersion
   * @return fileVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FILE_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFileVersion() {
    return fileVersion;
  }


  @JsonProperty(JSON_PROPERTY_FILE_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileVersion(String fileVersion) {
    this.fileVersion = fileVersion;
  }


  public ADCSInstanceDetailsResponse dnsName(String dnsName) {
    this.dnsName = dnsName;
    return this;
  }

   /**
   * Get dnsName
   * @return dnsName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DNS_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDnsName() {
    return dnsName;
  }


  @JsonProperty(JSON_PROPERTY_DNS_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDnsName(String dnsName) {
    this.dnsName = dnsName;
  }


  public ADCSInstanceDetailsResponse signingCerts(List<String> signingCerts) {
    this.signingCerts = signingCerts;
    return this;
  }

  public ADCSInstanceDetailsResponse addSigningCertsItem(String signingCertsItem) {
    if (this.signingCerts == null) {
      this.signingCerts = new ArrayList<>();
    }
    this.signingCerts.add(signingCertsItem);
    return this;
  }

   /**
   * Get signingCerts
   * @return signingCerts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNING_CERTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSigningCerts() {
    return signingCerts;
  }


  @JsonProperty(JSON_PROPERTY_SIGNING_CERTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSigningCerts(List<String> signingCerts) {
    this.signingCerts = signingCerts;
  }


  public ADCSInstanceDetailsResponse signingCertChains(List<String> signingCertChains) {
    this.signingCertChains = signingCertChains;
    return this;
  }

  public ADCSInstanceDetailsResponse addSigningCertChainsItem(String signingCertChainsItem) {
    if (this.signingCertChains == null) {
      this.signingCertChains = new ArrayList<>();
    }
    this.signingCertChains.add(signingCertChainsItem);
    return this;
  }

   /**
   * Get signingCertChains
   * @return signingCertChains
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNING_CERT_CHAINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSigningCertChains() {
    return signingCertChains;
  }


  @JsonProperty(JSON_PROPERTY_SIGNING_CERT_CHAINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSigningCertChains(List<String> signingCertChains) {
    this.signingCertChains = signingCertChains;
  }


  public ADCSInstanceDetailsResponse templates(List<String> templates) {
    this.templates = templates;
    return this;
  }

  public ADCSInstanceDetailsResponse addTemplatesItem(String templatesItem) {
    if (this.templates == null) {
      this.templates = new ArrayList<>();
    }
    this.templates.add(templatesItem);
    return this;
  }

   /**
   * Get templates
   * @return templates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEMPLATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTemplates() {
    return templates;
  }


  @JsonProperty(JSON_PROPERTY_TEMPLATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemplates(List<String> templates) {
    this.templates = templates;
  }


  public ADCSInstanceDetailsResponse templateOIDs(List<String> templateOIDs) {
    this.templateOIDs = templateOIDs;
    return this;
  }

  public ADCSInstanceDetailsResponse addTemplateOIDsItem(String templateOIDsItem) {
    if (this.templateOIDs == null) {
      this.templateOIDs = new ArrayList<>();
    }
    this.templateOIDs.add(templateOIDsItem);
    return this;
  }

   /**
   * Get templateOIDs
   * @return templateOIDs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEMPLATE_O_I_DS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTemplateOIDs() {
    return templateOIDs;
  }


  @JsonProperty(JSON_PROPERTY_TEMPLATE_O_I_DS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemplateOIDs(List<String> templateOIDs) {
    this.templateOIDs = templateOIDs;
  }


  public ADCSInstanceDetailsResponse subjectTemplateOIDs(List<String> subjectTemplateOIDs) {
    this.subjectTemplateOIDs = subjectTemplateOIDs;
    return this;
  }

  public ADCSInstanceDetailsResponse addSubjectTemplateOIDsItem(String subjectTemplateOIDsItem) {
    if (this.subjectTemplateOIDs == null) {
      this.subjectTemplateOIDs = new ArrayList<>();
    }
    this.subjectTemplateOIDs.add(subjectTemplateOIDsItem);
    return this;
  }

   /**
   * Get subjectTemplateOIDs
   * @return subjectTemplateOIDs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBJECT_TEMPLATE_O_I_DS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSubjectTemplateOIDs() {
    return subjectTemplateOIDs;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECT_TEMPLATE_O_I_DS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubjectTemplateOIDs(List<String> subjectTemplateOIDs) {
    this.subjectTemplateOIDs = subjectTemplateOIDs;
  }


  /**
   * Return true if this ADCSInstanceDetailsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ADCSInstanceDetailsResponse adCSInstanceDetailsResponse = (ADCSInstanceDetailsResponse) o;
    return Objects.equals(this.caName, adCSInstanceDetailsResponse.caName) &&
        Objects.equals(this.caType, adCSInstanceDetailsResponse.caType) &&
        Objects.equals(this.parentCaName, adCSInstanceDetailsResponse.parentCaName) &&
        Objects.equals(this.productVersion, adCSInstanceDetailsResponse.productVersion) &&
        Objects.equals(this.fileVersion, adCSInstanceDetailsResponse.fileVersion) &&
        Objects.equals(this.dnsName, adCSInstanceDetailsResponse.dnsName) &&
        Objects.equals(this.signingCerts, adCSInstanceDetailsResponse.signingCerts) &&
        Objects.equals(this.signingCertChains, adCSInstanceDetailsResponse.signingCertChains) &&
        Objects.equals(this.templates, adCSInstanceDetailsResponse.templates) &&
        Objects.equals(this.templateOIDs, adCSInstanceDetailsResponse.templateOIDs) &&
        Objects.equals(this.subjectTemplateOIDs, adCSInstanceDetailsResponse.subjectTemplateOIDs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caName, caType, parentCaName, productVersion, fileVersion, dnsName, signingCerts, signingCertChains, templates, templateOIDs, subjectTemplateOIDs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ADCSInstanceDetailsResponse {\n");
    sb.append("    caName: ").append(toIndentedString(caName)).append("\n");
    sb.append("    caType: ").append(toIndentedString(caType)).append("\n");
    sb.append("    parentCaName: ").append(toIndentedString(parentCaName)).append("\n");
    sb.append("    productVersion: ").append(toIndentedString(productVersion)).append("\n");
    sb.append("    fileVersion: ").append(toIndentedString(fileVersion)).append("\n");
    sb.append("    dnsName: ").append(toIndentedString(dnsName)).append("\n");
    sb.append("    signingCerts: ").append(toIndentedString(signingCerts)).append("\n");
    sb.append("    signingCertChains: ").append(toIndentedString(signingCertChains)).append("\n");
    sb.append("    templates: ").append(toIndentedString(templates)).append("\n");
    sb.append("    templateOIDs: ").append(toIndentedString(templateOIDs)).append("\n");
    sb.append("    subjectTemplateOIDs: ").append(toIndentedString(subjectTemplateOIDs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

