/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.trustable.ca3s.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * CertificateEnrollmentResponse
 */
@JsonPropertyOrder({
  CertificateEnrollmentResponse.JSON_PROPERTY_STATUS,
  CertificateEnrollmentResponse.JSON_PROPERTY_REQ_ID,
  CertificateEnrollmentResponse.JSON_PROPERTY_CERT,
  CertificateEnrollmentResponse.JSON_PROPERTY_CERT_C_A
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-01T16:42:19.029808700+02:00[Europe/Berlin]")
public class CertificateEnrollmentResponse {
  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_REQ_ID = "reqId";
  private Integer reqId;

  public static final String JSON_PROPERTY_CERT = "cert";
  private String cert;

  public static final String JSON_PROPERTY_CERT_C_A = "certCA";
  private String certCA;

  public CertificateEnrollmentResponse() { 
  }

  public CertificateEnrollmentResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(String status) {
    this.status = status;
  }


  public CertificateEnrollmentResponse reqId(Integer reqId) {
    this.reqId = reqId;
    return this;
  }

   /**
   * Get reqId
   * @return reqId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_REQ_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getReqId() {
    return reqId;
  }


  @JsonProperty(JSON_PROPERTY_REQ_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReqId(Integer reqId) {
    this.reqId = reqId;
  }


  public CertificateEnrollmentResponse cert(String cert) {
    this.cert = cert;
    return this;
  }

   /**
   * Get cert
   * @return cert
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CERT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCert() {
    return cert;
  }


  @JsonProperty(JSON_PROPERTY_CERT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCert(String cert) {
    this.cert = cert;
  }


  public CertificateEnrollmentResponse certCA(String certCA) {
    this.certCA = certCA;
    return this;
  }

   /**
   * Get certCA
   * @return certCA
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CERT_C_A)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCertCA() {
    return certCA;
  }


  @JsonProperty(JSON_PROPERTY_CERT_C_A)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCertCA(String certCA) {
    this.certCA = certCA;
  }


  /**
   * Return true if this CertificateEnrollmentResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateEnrollmentResponse certificateEnrollmentResponse = (CertificateEnrollmentResponse) o;
    return Objects.equals(this.status, certificateEnrollmentResponse.status) &&
        Objects.equals(this.reqId, certificateEnrollmentResponse.reqId) &&
        Objects.equals(this.cert, certificateEnrollmentResponse.cert) &&
        Objects.equals(this.certCA, certificateEnrollmentResponse.certCA);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, reqId, cert, certCA);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateEnrollmentResponse {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    reqId: ").append(toIndentedString(reqId)).append("\n");
    sb.append("    cert: ").append(toIndentedString(cert)).append("\n");
    sb.append("    certCA: ").append(toIndentedString(certCA)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

