/*
 * ADCSConnector
 * baseline API to request and revoce certificates from an ADCS instace
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: kuehne@trustable.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.trustable.ca3s.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * CertificateRequestElements
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-08T20:19:50.781Z[GMT]")
public class CertificateRequestElements {
  @SerializedName("csr")
  private String csr = null;

  @SerializedName("attributes")
  private List<CertificateRequestElementsAttributes> attributes = new ArrayList<CertificateRequestElementsAttributes>();

  public CertificateRequestElements csr(String csr) {
    this.csr = csr;
    return this;
  }

   /**
   * Get csr
   * @return csr
  **/
  public String getCsr() {
    return csr;
  }

  public void setCsr(String csr) {
    this.csr = csr;
  }

  public CertificateRequestElements attributes(List<CertificateRequestElementsAttributes> attributes) {
    this.attributes = attributes;
    return this;
  }

  public CertificateRequestElements addAttributesItem(CertificateRequestElementsAttributes attributesItem) {
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  public List<CertificateRequestElementsAttributes> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<CertificateRequestElementsAttributes> attributes) {
    this.attributes = attributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateRequestElements certificateRequestElements = (CertificateRequestElements) o;
    return Objects.equals(this.csr, certificateRequestElements.csr) &&
        Objects.equals(this.attributes, certificateRequestElements.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(csr, attributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateRequestElements {\n");
    
    sb.append("    csr: ").append(toIndentedString(csr)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
